### ISSUE TITLE
ERROR: Invalid parameters. Maybe URL is incorrect.

### ISSUE THREAD

**Issue by hirokita10** [ryuta69/xvideo-youtube-niconico-soundcloud-download#1]
readme通りにと試して見たらエラーが出てしまいました。
また後日、ソースとログ詳しく調べてみます！
Python 3.6.4

ERROR: Invalid parameters. Maybe URL is incorrect.
Traceback (most recent call last):
  File "main.py", line 26, in <module>
    subprocess.check_call(cmd.split())
  File "/Users/mac/.pyenv/versions/3.6.4/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['youtube-dl', '-o', './%(playlist)s/%(title)s.%(ext)s', '-i', '-f', 'mp4', '--add-metadata', 'PLZWB2wzAxoVAIBVUqCZ84jqOyMKzLSVUqf']' returned non-zero exit status 1.

**Comment by ryuta69** [comment]
@hirokita10 さん
subprocessが失敗しているみたいですね

①
brew update
brew upgrade youtube-dl

②
youtube-dlとコマンドで打って正しく動作しているか

③
./%(playlist)s/%(title)s.%(ext)s
を
%(playlist)s/%(title)s.%(ext)s
に変更する

の３つを試して頂けますか

**Comment by ryuta69** [comment]
違う！
https://www.youtube.com/playlist?list=PLZWB2wzAxoVAIBVUqCZ84jqOyMKzLSVUq
が正しいURLでした

テスト用に消してしまったURLの方をreadmeに書いてました
申し訳ありません、今一度プルしてお試し下さい！

**Comment by hirokita10** [comment]
無事成功しました！
ありがとうございます！！！！
youtubeの場合は動画ページurlではなく、一旦プレイリストに入れて、
プレイリストurlを指定しなければいけないようですね。

**Comment by ryuta69** [comment]
@hirokita10 さん
ああ！！！
ごめんなさい、それ普通に僕のケアレスミスです！

今プッシュしたコードで、普通に動画URLでもDL可能になってます！
ご確認ください！

**Comment by hirokita10** [comment]
迅速な対応本当にありがとうございます！！
成功しました！！！！
